<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('productos')->insert([
            [
                'nombreP' => 'Billetera', 
                'descripcionP' => 'Billetera de cuero',
                'materialP' => 'Cuero',
                'precioP' => 50.00, 
                'stock' => 10,
                'colorP' => 'Negro', 
                'tipoP' => 'Accesorio',
                'imgP' => 'imagen/gallery-img-02.jpg',
                'imgP2' => 'imagen/gallery-img-02.jpg',
                'imgP3' => 'imagen/gallery-img-02.jpg', 
                'descuentoP' => 10,
                'metodoP' => 'Online',
                'costoEnvio' => 10,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 1, // Artículos de Cuero
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Cartera', 
                'descripcionP' => 'Cartera de cuero',
                'materialP' => 'Cuero',
                'precioP' => 120.00, 
                'stock' => 20,
                'colorP' => 'Marrón', 
                'tipoP' => 'Accesorio',
                'imgP' => 'imagen/gallery-img-04.jpg',
                'imgP2' => 'imagen/gallery-img-04.jpg',
                'imgP3' => 'imagen/gallery-img-04.jpg', 
                'descuentoP' => 2,
                'metodoP' => 'Online',
                'costoEnvio' => 12,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 1,
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Sandalias', 
                'descripcionP' => 'Sandalias de cuero',
                'materialP' => 'Cuero',
                'precioP' => 89.99, 
                'stock' => 15,
                'colorP' => 'Beige', 
                'tipoP' => 'Calzado',
                'imgP' => 'imagen/gallery-img-06.jpg',
                'imgP2' => 'imagen/gallery-img-06.jpg',
                'imgP3' => 'imagen/gallery-img-06.jpg', 
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 14,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 1,
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Mochila', 
                'descripcionP' => 'Mochila de cuero con aguayo',
                'materialP' => 'Cuero y Aguayo',
                'precioP' => 700.00, 
                'stock' => 8,
                'colorP' => 'Multicolor', 
                'tipoP' => 'Accesorio',
                'imgP' => 'imagen/p26_mochila.jpg',
                'imgP2' => 'imagen/p26_mochila.jpg',
                'imgP3' => 'imagen/p26_mochila.jpg', 
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 20,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 1,
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Cinturón', 
                'descripcionP' => 'Cinturón de cuero con aguayo',
                'materialP' => 'Cuero y Aguayo',
                'precioP' => 50.00, 
                'stock' => 12,
                'colorP' => 'Negro', 
                'tipoP' => 'Accesorio',
                'imgP' => 'imagen/p27_cinturon.jpg',
                'imgP2' => 'imagen/p27_cinturon.jpg',
                'imgP3' => 'imagen/p27_cinturon.jpg', 
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 10,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 1,
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Cesto', 
                'descripcionP' => 'Cesto de paja',
                'materialP' => 'Paja',
                'precioP' => 20.00, 
                'stock' => 5,
                'colorP' => 'Natural', 
                'tipoP' => 'Decoración',
                'imgP' => 'imagen/p2.jpg',
                'imgP2' => 'imagen/p2.jpg',
                'imgP3' => 'imagen/p2.jpg', 
                'descuentoP' => 5,
                'metodoP' => 'Online',
                'costoEnvio' => 10,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 2,
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Alfombra', 
                'descripcionP' => 'Alfombra multicolor',
                'materialP' => 'Textil',
                'precioP' => 800.00, 
                'stock' => 7,
                'colorP' => 'Multicolor', 
                'tipoP' => 'Decoración',
                'imgP' => 'imagen/p4.webp',
                'imgP2' => 'imagen/p4.webp',
                'imgP3' => 'imagen/p4.webp', 
                'descuentoP' => 10,
                'metodoP' => 'Online',
                'costoEnvio' => 20,
                'tiempoEntrega' => 2,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 2,
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Panero', 
                'descripcionP' => 'Panero de paja',
                'materialP' => 'Paja',
                'precioP' => 250.00, 
                'stock' => 8,
                'colorP' => 'Natural', 
                'tipoP' => 'Decoración',
                'imgP' => 'imagen/p5.webp',
                'imgP2' => 'imagen/p5.webp',
                'imgP3' => 'imagen/p5.webp', 
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 10,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 2,
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Bolsa de aguayo', 
                'descripcionP' => 'Bolsa de lana multicolor',
                'materialP' => 'Lana',
                'precioP' => 30.00, 
                'stock' => 12,
                'colorP' => 'Multicolor', 
                'tipoP' => 'Accesorio',
                'imgP' => 'imagen/p12_bolsa.JPG',
                'imgP2' => 'imagen/p12_bolsa.JPG',
                'imgP3' => 'imagen/p12_bolsa.JPG', 
                'descuentoP' => 12,
                'metodoP' => 'Online',
                'costoEnvio' => 10,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 3,
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Poncho', 
                'descripcionP' => 'Poncho rojo',
                'materialP' => 'Textil',
                'precioP' => 400.00, 
                'stock' => 5,
                'colorP' => 'Rojo', 
                'tipoP' => 'Textil',
                'imgP' => 'imagen/p13_poncho.jpg',
                'imgP2' => 'imagen/p13_poncho.jpg',
                'imgP3' => 'imagen/p13_poncho.jpg', 
                'descuentoP' => 10,
                'metodoP' => 'Online',
                'costoEnvio' => 10,
                'tiempoEntrega' => 2,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 3,
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Joyero', 
                'descripcionP' => 'Joyero azul',
                'materialP' => 'Madera',
                'precioP' => 65.00, 
                'stock' => 4,
                'colorP' => 'Azul', 
                'tipoP' => 'Joyería',
                'imgP' => 'imagen/p14_joyero.jpg',
                'imgP2' => 'imagen/p14_joyero.jpg',
                'imgP3' => 'imagen/p14_joyero.jpg', 
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 10,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 4,
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Arete', 
                'descripcionP' => 'Pendientes de plata 950',
                'materialP' => 'Plata',
                'precioP' => 168.00, 
                'stock' => 15,
                'colorP' => 'Plata', 
                'tipoP' => 'Joyería',
                'imgP' => 'imagen/p15_joya.jpg',
                'imgP2' => 'imagen/p15_joya.jpg',
                'imgP3' => 'imagen/p15_joya.jpg', 
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 10,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 4,
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Jarrón', 
                'descripcionP' => 'Jarrón decorativo',
                'materialP' => 'Cerámica',
                'precioP' => 350.00, 
                'stock' => 6,
                'colorP' => 'Blanco', 
                'tipoP' => 'Decoración',
                'imgP' => 'imagen/p16_jarron.jpg',
                'imgP2' => 'imagen/p16_jarron.jpg',
                'imgP3' => 'imagen/p16_jarron.jpg', 
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 0,
                'tiempoEntrega' => 0,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 3,
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Charango', 
                'descripcionP' => 'Charango de madera',
                'materialP' => 'Madera',
                'precioP' => 1200.00, 
                'stock' => 3,
                'colorP' => 'Natural', 
                'tipoP' => 'Instrumento',
                'imgP' => 'imagen/p18_CHARANGO.jpg',
                'imgP2' => 'imagen/p18_CHARANGO.jpg',
                'imgP3' => 'imagen/p18_CHARANGO.jpg', 
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 14,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 5,
                'created_at' => now(), 
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Juego de ajedrez', 
                'descripcionP' => 'Juego de ajedrez de madera',
                'materialP' => 'Madera',
                'precioP' => 550.00, 
                'stock' => 2,
                'colorP' => 'Madera', 
                'tipoP' => 'Juego',
                'imgP' => 'imagen/p19_ajedrez.jpg',
                'imgP2' => 'imagen/p19_ajedrez.jpg',
                'imgP3' => 'imagen/p19_ajedrez.jpg', 
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 10,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 5,
                'created_at' => now(), 
                'updated_at' => now()
            ],

            [
                'nombreP' => 'Posa vaso',
                'descripcionP' => 'Posa vaso de café',
                'materialP' => 'Madera',
                'precioP' => 15.00,
                'stock' => 10,
                'colorP' => 'Café',
                'tipoP' => 'Accesorio',
                'imgP' => 'imagen/p20_posavaso.jpg',
                'imgP2' => 'imagen/p20_posavaso.jpg',
                'imgP3' => 'imagen/p20_posavaso.jpg',
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 10,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 3, // Decoración
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Servilletero',
                'descripcionP' => 'Servilletero decorativo',
                'materialP' => 'Madera',
                'precioP' => 20.00,
                'stock' => 8,
                'colorP' => 'Natural',
                'tipoP' => 'Accesorio',
                'imgP' => 'imagen/p21_servilletero.jpg',
                'imgP2' => 'imagen/p21_servilletero.jpg',
                'imgP3' => 'imagen/p21_servilletero.jpg',
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 10,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 3,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Individual',
                'descripcionP' => 'Individual rojo y naranja de oveja de lana',
                'materialP' => 'Lana',
                'precioP' => 30.00,
                'stock' => 5,
                'colorP' => 'Rojo y Naranja',
                'tipoP' => 'Textil',
                'imgP' => 'imagen/p22_individual.jpg',
                'imgP2' => 'imagen/p22_individual.jpg',
                'imgP3' => 'imagen/p22_individual.jpg',
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 10,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 4, // Textiles
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Azucarera',
                'descripcionP' => 'Azucarera turquesa',
                'materialP' => 'Cerámica',
                'precioP' => 50.00,
                'stock' => 6,
                'colorP' => 'Turquesa',
                'tipoP' => 'Decoración',
                'imgP' => 'imagen/p23_azucarera.jpg',
                'imgP2' => 'imagen/p23_azucarera.jpg',
                'imgP3' => 'imagen/p23_azucarera.jpg',
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 10,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 3,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Manta',
                'descripcionP' => 'Manta roja de aguayo',
                'materialP' => 'Aguayo',
                'precioP' => 130.00,
                'stock' => 4,
                'colorP' => 'Rojo',
                'tipoP' => 'Textil',
                'imgP' => 'imagen/p24_manta.jpg',
                'imgP2' => 'imagen/p24_manta.jpg',
                'imgP3' => 'imagen/p24_manta.jpg',
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 13,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 4,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Funda de almohada',
                'descripcionP' => 'Funda de almohada blanca',
                'materialP' => 'Textil',
                'precioP' => 89.00,
                'stock' => 10,
                'colorP' => 'Blanco',
                'tipoP' => 'Textil',
                'imgP' => 'imagen/p25_funda.jpg',
                'imgP2' => 'imagen/p25_funda.jpg',
                'imgP3' => 'imagen/p25_funda.jpg',
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 8,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 4,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Anillo',
                'descripcionP' => 'Anillo en forma ondulada con dos piedras engarzadas de circón',
                'materialP' => 'Plata y Circón',
                'precioP' => 1350.00,
                'stock' => 5,
                'colorP' => 'Plateado',
                'tipoP' => 'Joyería',
                'imgP' => 'imagen/p28_anillo.jpg',
                'imgP2' => 'imagen/p28_anillo.jpg',
                'imgP3' => 'imagen/p28_anillo.jpg',
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 20,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 5, // Joyería
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombreP' => 'Arete',
                'descripcionP' => 'Pendientes delicados y finamente trabajados, perfectos para un estilo juvenil y moderno.',
                'materialP' => 'Plata',
                'precioP' => 630.00,
                'stock' => 15,
                'colorP' => 'Plata',
                'tipoP' => 'Joyería',
                'imgP' => 'imagen/p29_arete.jpg',
                'imgP2' => 'imagen/p29_arete.jpg',
                'imgP3' => 'imagen/p29_arete.jpg',
                'descuentoP' => 0,
                'metodoP' => 'Online',
                'costoEnvio' => 15,
                'tiempoEntrega' => 1,
                'devolucionP' => '30 días garantizados',
                'garantiaP' => 12,
                'certificacionP' => 'ISO 9001',
                'autP' => 1,
                'id_categoria' => 5,
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);
    }
}
